### ISSUE TITLE
Documentation for modifying chrome args to load custom profiles or extensions. 

### ISSUE THREAD

**Issue by conkonig** [google/pageloader#113]
Please include documentation for how to modify chrome arguments to load chrome profiles or extensions. 

At the moment I am really struggling with the lack of web driver and selenium to deal with basic authentication now that URL encoding is unsupported. 

How and in what format can I add necessary parameters such as:
 –start-maximized 
--user-data-dir=pathToUserProfile
–load-extension=pathToChromeExtension

into the below from pageloader/dart/async/test/setup/webdriver_test_setup.dart:

  if (env['CHROMEDRIVER_ARGS'] != null) {
    chromeOptions['args'] = env['CHROMEDRIVER_ARGS'].split(' ');
  }

**Comment by con-king** [comment]
I am asking because I have a chrome extension that handles the authentication - alternatively any link to a working implementation of basic authentication with web-driver in dart would be sincerely appreciated.
