### ISSUE TITLE
All page object fields are null under Dart 2-dev.17 when using dartdevc

### ISSUE THREAD

**Issue by chalin** [google/pageloader#114]
Pageloader is used by angular_test.

Angular example app tests using pageloader have stopped working recently due to page object fields not getting bound. This happens as of Dart 2.0.0-dev.17, Angular 5.0.0-alpha+3, which requires use of the dartdevc web compiler. The same tests were running fine under Dart 2.0-dev.16 and Angular 5.0.0-alpha+2.

See https://github.com/dart-lang/angular/issues/783 for full details.

cc @kwalrath @matanlurey @kevmoo

**Comment by kevmoo** [comment]
@chalin – please check w/ v3 and reopen if this is still an issue
