### ISSUE TITLE
Upgrade to source_gen ^0.8.0

### ISSUE THREAD

**Issue by chalin** [google/pageloader#122]
Pageloader at HEAD is using source_gen ^0.7.0.

I'm eager to upgrade Angular example app tests to the new pageloader, but Angular is already using source_gen ^0.8.0. (There may be other issues, but this seemed like the first hurdle.)

cc @kwalrath @kevmoo

**Comment by kevmoo** [comment]
See https://github.com/google/pageloader/pull/123
