### ISSUE TITLE
Provide concrete examples for creating a PO

### ISSUE THREAD

**Issue by chalin** [google/pageloader#127]
From the README:

> Construction of these PageObjects are easy; call the 'create' constructor
> and pass in the context. You want the `<html>` node for tests.
>
> ```dart
>  final myPO = new MyPO.create(pageLoaderElementContext);
>  ```

It may be "easy" to create POs, but there should be at least one concrete example of how to do so. I'm not sure, but I think that the following should work:

```dart
  Element htmlElement = ...;
  final context = new HtmlPageLoaderElement.createFromElement(htmlElement);
  final myPO = new MyPO.create(context);
```

Is the above correct? If so, I don't mind submitting a PR.

It might also be a good idea to explain when it is a good idea to provide a `SyncFn` (an example of that would be nice too).

cc @kevmoo @kwalrath

**Comment by kevmoo** [comment]
CC @mk13

**Comment by mk13** [comment]
Thanks for raising this issue. I'll update the README.md shortly to reflect both HtmlPageLoaderElement and WebdriverPageloaderElement construction (as well as syncFn for HtmlPageLoaderElement).

**Comment by kevmoo** [comment]
Closed by https://github.com/google/pageloader/pull/129 ?

**Comment by chalin** [comment]
Yes, closing. I'm eager to try it once the [build issues](https://github.com/dart-lang/build/issues/1426#issuecomment-388968415) are ironed out.
