### ISSUE TITLE
Release 3.0.0-beta

### ISSUE THREAD

**Issue by kevmoo** [google/pageloader#130]
Any there specific items we should validate before we release?

Sanity check w/ @chalin ?

CC @mk13 

Let's make sure to discuss before we do this...

**Comment by chalin** [comment]
I'm working on the conversion of all of the component tests for all the Angular example apps. That would certainly be a good basis for validation. I can post here once I'm done.

**Comment by kevmoo** [comment]
Awesome!

**Comment by chalin** [comment]
The pageloader-builder-generated `*.g.dart` files get written to the original source folder. Can we ensure that they are instead saved where ever the Angular `*.template.dart` files are saved (which includes the build output folder when it is specified)?

Maybe this has to do with the use of `part of "foo.g.dart"`. That is another thing that Angular is able to avoid. It is a lot more convenient to be able to `import "foo.g.dart" as bar` to avoid errors from tools even when the .g.dart file isn't present.

cc @natebosch @kwalrath

**Comment by chalin** [comment]
Btw, how about releasing 3.0.0-alpha first. That way I'll be able to pickup the package from pub, and be able to test links into the API docs.

**Comment by kevmoo** [comment]
> how about releasing 3.0.0-alpha first

@chalin – are you ready for an alpha release? Does the code as-is seem to work?

**Comment by chalin** [comment]
**Status update** for today: I've successfully converted 6 of the 9 example app projects that have component tests. The one with the largest test suite is **toh-5**: you can see the file changes in [this commit](https://github.com/dart-lang/site-webdev/pull/1585/commits/9f25f0bcef8b08c0418c4e978b39500b9aed486f) (or view the [entire PR](https://github.com/dart-lang/site-webdev/pull/1585)). I'll complete the conversion tomorrow.

Btw, it's great to be able to drop the unnecessary **async**-ness!

**Comment by kevmoo** [comment]
@mk13 – are we ready to call beta here?

**Comment by mk13** [comment]
I'm finishing up one more requested feature, then we can announce the beta.

**Comment by mk13** [comment]
Released!
