### ISSUE TITLE
Release 3.0.0-alpha

### ISSUE THREAD

**Issue by chalin** [google/pageloader#131]
From https://github.com/google/pageloader/issues/130#issuecomment-389249676:

> @chalin – are you ready for an alpha release? Does the code as-is seem to work?

Yes and yes!

The only issue is incompatibility with angular_components (https://github.com/dart-lang/angular_components/issues/263), but I'm assuming that that isn't blocking for an alpha release.

cc @kwalrath @mk13

**Comment by chalin** [comment]
@mk13 - is anything holding back either a 3.0.0-dev or a 3.0.0-alpha release of the pageloader? /cc @kevmoo

**Comment by mk13** [comment]
@kevmoo 
Any concerns about releasing alpha?

**Comment by kevmoo** [comment]
Nope! Let's get it out there...

**Comment by chalin** [comment]
HEAD has 3.0.0-alpha 🎉: https://github.com/google/pageloader/blob/018a8e385f5d1d457ab0de7cb3de4beed31e67f8/pubspec.yaml#L3

Will this be published soon?

**Comment by mk13** [comment]
Soon. I’m doing one last sync up check internally. I noticed a bug with the matchers. Currently working on a patch for this.

As soon as I see this green internally as well, I’ll publish.

**Comment by mk13** [comment]
Just published: https://pub.dartlang.org/packages/pageloader/versions/3.0.0-alpha

**Comment by chalin** [comment]
\o/

**Comment by kevmoo** [comment]
Want to put it back into stagehand?

**Comment by chalin** [comment]
> Want to put it back into stagehand?

Yes! I've added as an item to https://github.com/dart-lang/site-webdev/issues/1351
