### ISSUE TITLE
Save generated files to build output folder not the original source folder

### ISSUE THREAD

**Issue by chalin** [google/pageloader#132]
From https://github.com/google/pageloader/issues/130#issuecomment-389108435:

> The pageloader-builder-generated `*.g.dart` files get written to the original source folder. Can we ensure that they are instead saved where ever the Angular `*.template.dart` files are saved (which includes the build output folder when it is specified)?
> 
> Maybe this has to do with the use of `part of "foo.g.dart"`. That is another thing that Angular is able to avoid. It is a lot more convenient to be able to `import "foo.g.dart" as bar` to avoid errors from tools even when the .g.dart file isn't present.
> 
> cc @natebosch @kwalrath

**Comment by natebosch** [comment]
The question of whether to output to source vs the generated directory comes down to a question of whether the files are "valid" if they are used in a project with a different versions of dependencies.

If I `pub get` and end up with a different set of packages than you did when you ran a build - am I going to run in to trouble using the page objects? Do they depend on details from within the pageloader package (that may change without a breaking version bump) for instance?

**Comment by mk13** [comment]
I think one possible issue that could arise is the usage of `part` directive. Currently given some po file, `my_po.dart` it has the directive `part 'my_po.g.dart';`.

If the generated file is being stored in a cache folder rather that directly in the same directory, we would have:

`part '<cache location>/my_po.g.dart';`

Correct me if I'm wrong, but I think this would happen. I would like to avoid this entirely. I'll try some experiments if I can find a different implementation of the generated files to avoid this. For alpha/beta release, I think we can stick with what we have now.

This wouldn't be trivial, but if I can find a solution while also removing a lot of the unnecessary boilerplate, it would be amazing.

**Comment by natebosch** [comment]
> Correct me if I'm wrong, but I think this would happen.

You're wrong 😉 

The apparent view of these files when we invoke the compiler is as if they were in the same directory. Eventually the analyzer will also see it this way - you won't get an error after the first build for the file being missing and a jump-to-definition will take you to the file in the generated cache.

**Comment by mk13** [comment]
Oh, that's good news! :D

**Comment by chalin** [comment]
Nate, is there an equivalent of `import 'foo.g.dart' as bar` for the `part` statement? (I'm not aware of any.) Also, do you know if the analyzer option `uri_has_not_been_generated` also applies to `part` statements?

**Comment by natebosch** [comment]
> is there an equivalent of `import 'foo.g.dart' as bar` for the `part` statement?

No, part files are _in_ this library so it's closer to inlining the code than importing it.

> Also, do you know if the analyzer option `uri_has_not_been_generated` also applies to `part` statements?

Yes I'm pretty sure it does.

**Comment by chalin** [comment]
> Yes I'm pretty sure it does.

Actually, I just remembered that I have `uri_has_not_been_generated` set to `ignore` in all of the example app `analysis_options.yaml` files (see below for an example), and I was getting an error reported over `part 'foo.g.dart'` until it got generated. Maybe there is an extra analyzer config option that is needed?

```yaml
analyzer:
  ...
  errors:
    uri_has_not_been_generated: ignore
```

**Comment by natebosch** [comment]
> Maybe there is an extra analyzer config option that is needed?

Analyzer support for `.dart_tool/build/generated/` in general is not available yet, once it is these errors should ago away.

**Comment by natebosch** [comment]
Another thing we should consider if we do change it to build to the cache is to pick a different extension other than `.g.dart`. Our eventual solution for letting multiple `source_gen` generators build to the same part file at `.g.dart` will only work if they _all_ want to build to source. If we're building to cache we should pick a different name.

**Comment by landoulsi** [comment]
Another temp solution that can be done even by a simple script is to move the generated code of the file `.g.dart` to the bottom of the source file to avoid having multiple useless files.
I have done today this script and can share with anyone interested.

**Comment by natebosch** [comment]
> move the generated code of the file `.g.dart` to the bottom of the source file

This isn't something supported by the build system and isn't something we'd recommend in general.
