### ISSUE TITLE
Relax the file restriction once build_runner long-term is released

### ISSUE THREAD

**Issue by mk13** [google/pageloader#134]
Temporary rule is in place: PO dart files must be in `test/`

Remove this restriction once build_runner doesn't have conflicts with running multiple builders on same suffix (ex: `*.g.dart`).

**Comment by chalin** [comment]
@mk13 - #133 evolved based on feedback and so the restrictions have changed. I'll be referring to this issue in the docs. Could you update the original text of the issue to reflect the only remaining limitation? This is (tentatively) how I'll be describing the limitation in the docs:

> [Ensure that the PO source file] does not contain any Angular annotations (like `@Component` or `@GenerateInjector`) that would trigger the Angular builder. This is a temporary limitation; for details, see [pageloader issue #134](https://github.com/google/pageloader/issues/134).

cc @kwalrath @natebosch

**Comment by chalin** [comment]
Thanks for the feedback @natebosch.

> A builder going from .dart to .g.dart will never conflict with Angular

As you know from [build issue #1426](https://github.com/dart-lang/build/issues/1426), we were having a conflict with a test file (`app_test.dart`) that used to contain both `angular_test`-based tests _and_ the PO class.

> The limitation is not based on file content. We determine conflicts statically based on file names and builder config, not by reading files. ...

Ok, well we need a simple way to articulation the limitation that will make sense to most developers (including novices). Was @jakemac53 supposed to help with that? :)

**Comment by natebosch** [comment]
> As you know from build issue #1426, we were having a conflict with a test file (app_test.dart) that used to contain both angular_test-based tests and the PO class.

That conflict was likely coming from `built_value`, not angular. I need to find time to fix https://github.com/dart-lang/build/issues/1273 which would make this more clear.

**Comment by chalin** [comment]
LGTM @natebosch.

@mk13 - why are both pageloader and the built_value_generator writing to the same file. Actually, isn't the pageloader builder using built_value_generator? If so, why is there a conflict then?
