### ISSUE TITLE
Avoid unnecessary new and const in generated code

### ISSUE THREAD

**Issue by chalin** [google/pageloader#152]
It seems reasonable require that the generated code pass the `unnecessary_const` and `unnecessary_new` lints. Can this happen before 3.0.0 final?

cc @kevmoo @kwalrath

**Comment by mk13** [comment]
We're currently not detecting these lints in pageloader: https://github.com/google/pageloader/blob/master/analysis_options.yaml

Is this lint an optional thing or now considered the norm? I'm not sure about others, but I quite like the usage of 'new'/'const' keyword.

**Comment by chalin** [comment]
I believe that we'd like to omit unnecessary `new` and `const` in all Dart 2 code.

It is currently tricky (see https://github.com/dart-lang/sdk/issues/34053 to be able to use `unnecessary_const` and `unnecessary_new` in projects using pageloader because there are issues with the analyzer command line preventing us from easily (directly) excluding pageloader generated files).

@kevmoo any opinion about this?

**Comment by mk13** [comment]
Oh I see, I'll remove them then for now.

**Comment by kevmoo** [comment]
SGTM

**Comment by mk13** [comment]
Done, will be published with 3.0.0
