### ISSUE TITLE
Rename notExists to doesNotExist

### ISSUE THREAD

**Issue by leiboldm** [google/pageloader#159]
Relevant sections from effective dart:

https://www.dartlang.org/guides/language/effective-dart/design#consider-making-the-code-read-like-a-sentence

https://www.dartlang.org/guides/language/effective-dart/design#prefer-a-noun-phrase-or-non-imperative-verb-phrase-for-a-function-or-method-if-returning-a-value-is-its-primary-purpose

**Comment by mk13** [comment]
Won't be fixing due the the wide-spread usage internally already.
