### ISSUE TITLE
Bump analyzer version

### ISSUE THREAD

**Issue by chalin** [google/pageloader#169]
We're having issues building Angular examples that make use of pageloader (https://github.com/dart-lang/site-webdev/issues/1834).

Angular 5.2.0 depends on the analyzer v0.34 (and Angular 5.1.0 depends on the analyzer v0.33), but pageloader 3.0.2 still requires v0.32 (according to [its pub version info](https://pub.dartlang.org/packages/pageloader#-analysis-tab-)). I see that at HEAD it is now `analyzer: ^0.33.3`.

Could the `analyzer` constraint be made 0.34 or at least to include 0.34?

cc @kwalrath @kevmoo

**Comment by manuscle** [comment]
:+1: 
Waiting for the upgrade, is there a way to force pageloader install?
I cannot install it anymore

**Comment by kevmoo** [comment]
CC @mk13 ?

**Comment by mk13** [comment]
Please verify. I don't think I need to publish a new version, but let me know if I do.

**Comment by chalin** [comment]
Actually, I'll need this to be published.

**Comment by mk13** [comment]
Published.

**Comment by chalin** [comment]
Thank you!

@kwalrath, do you want to give it a try using the template-syntax example?

**Comment by kwalrath** [comment]
Will do. Thanks, everyone!

**Comment by kwalrath** [comment]
It works now! I was able to upgrade template-syntax:
* dart-lang/site-webdev#1876
* angular-examples/template-syntax [master](https://github.com/angular-examples/template-syntax/commits/master)
* angular-examples/template-syntax [gh-pages](https://github.com/angular-examples/template-syntax/commits/gh-pages)

**Comment by mk13** [comment]
Thanks! I'll close this ticket then.

**Comment by manuscle** [comment]
Great! Thank you ! :smiley:
