### ISSUE TITLE
Add analyzer 0.40.0 support

### ISSUE THREAD

**Issue by LukeyBeachBoy** [google/pageloader#210]
`type` and `isObject` are deprecated as of [analyzer 0.40.0](https://pub.dev/packages/analyzer), this causes build issues in cases where `analyzer >=0.40.0 <0.40.7` is needed in the same project as `pageloader`.

They should be replaced with `thisType` and `isDartCoreObject` respectively.

**Comment by valakis** [comment]
It would be really helpful, because the newest angular (6.0.1) can't be used with the pageloader currently

**Comment by jguitar** [comment]
There is a PR for this #211

**Comment by mk13** [comment]
v3.3.2 resolves this.
