### ISSUE TITLE
Non-null safe Angular 6 compatibility

### ISSUE THREAD

**Issue by daniel-v** [google/pageloader#216]
Could we have a version of this library that is compatible with Angular 6? Would be also nice if we could opt out of null-safe attempts until it is more mature.

**Comment by mk13** [comment]
`v3.3.2` and `v.4.0.0` has been released. Both versions should be compatible with Angular 6.

`v3.3.2` is non-null safe (SDK <2.12.0). `v4.0.0` is unsound null safe, but can still be used on pageloader files that are not fully migrated yet. You can simply add a `// @dart = 2.9` at the top of the file.

For example:

```dart
// @dart = 2.9

import 'package:pageloader/pageloader.dart';

@PageObject()
abstract class FooPO { ... }
```
