### ISSUE TITLE
sync: add blur method that is supported in async already

### ISSUE THREAD

**Issue by BlackHC** [google/pageloader#52]
Async has it. We need it in sync as well for Adwords for Video. For this, sync_webdriver also has to be updated probably.

**Comment by DrMarcII** [comment]
sync pageloader is not supported, and well eventually be deleted from this project.

**Comment by BlackHC** [comment]
I'm sorry but are going to keep using it for the near future at least and
we need this feature. Shall I file an internal bug instead?

Thanks,
Andreas
