### ISSUE TITLE
Divide async and sync dart version into two separate packages

### ISSUE THREAD

**Issue by goderbauer** [google/pageloader#66]
I would like to separate the dart version of pageloader into two separate pub packages: One for sync and the other for the async version (similar to how async and sync webdriver.dart is separate).
 
Advantages:
* cleaner dependencies (async pageloader doesn't need to depend on sync webdriver)
* easier to deprecate sync pageloader when it is a separate package
* versions for async and sync can increase independently

I would suggest keeping both versions in this github repository. I would just change the directory structure from `dart/lib/async` and `dart/lib/sync` to `dart/async/lib` and `dart/sync/lib`. The same change would be applied to the other directories (`test`, etc).

@DrMarcII Any objections?

**Comment by srawlins** [comment]
+1; you can then have a `dart/async/pubspec.yaml` and a `dart/sync/pubspec.yaml`.

**Comment by goderbauer** [comment]
@srawlins That is the idea. There will then be two packages on pub.dartlang.org: `pageloader` and `sync_pageloader`. This is similar to how we have `webdriver` and `sync_webdriver` as packages.

**Comment by BlackHC** [comment]
Great idea! This will make deprecation easier and untangle dependencies.

**Comment by goderbauer** [comment]
PR implementing this proposal has been merged. Thanks everybody for your input!
